name: Docker Image CI

on:
  push:
    braches: ["main"]
    
jobs:

  build:
  
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v3
  
  -name: Build the Docker image
   run: docker build . --file Dockerfile --ta hello:$(date +%s)
