name: Docker Image CI

on:
  push:
    braches: ["main"]
    
jobs:

  build:
  
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v3
  
  -name: Build the Docker image
   run: docker build . --file Dockerfile --ta hello:$(date +%s)
   
  -name: Sysdig secure inline scan
  
 curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/darwin/arm64/sysdig-cli-scanner" 
 chmod +x ./sysdig-cli-scanner
 
